apiVersion: v1
kind: Secret
metadata:
  name: {{ include "springboot-mysql.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_PASSWORD: "{{ .Values.mysql.password }}"
