apiVersion: v1
kind: Service
metadata:
  name: {{ include "springboot-mysql.fullname" . }}-mysql
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    app: {{ include "springboot-mysql.fullname" . }}-mysql
