namespace: app-namespace

replicaCount: 2

image:
  repository: filekrafter95/springboot-mysql
  tag: 1.0.1
  pullPolicy: IfNotPresent

mysql:
  image: mysql:8
  rootPassword: myrootpass
  database: appdb
  user: appuser
  password: appuserpass

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  host: springboot.local
  className: nginx

config:
  appName: SpringBootHelmApp
